#!/bin/bash
##
## vRouter/DPDK tcpdump
##

## Constants
MON_IF_NAME="mon"
VR_MAX_INTERFACES=$((256 + 4096))
MON_TYPE="monitoring"

## Functions
usage () {
    echo "vRouter/DPDK vif tcmpdump script"
    echo "Usage:"
    echo "      ${0##*/} <vif index> [tcpdump arguments]"
    echo "              - to run tcpdump on a specified vif"
    echo "      ${0##*/} stop <vif index>"
    echo "              - to force stop the monitoring and clean up the vif specified"
    echo "Example:"
    echo "      ${0##*/} 1 -nvv"
    exit 1
}

error () {
    echo -e "${0##*/} error: $1"
    exit 1
}

monitoring_stop () {
    if [ $# -lt 1 ]; then
        usage
    fi
    echo "Deleting vif ${1}..."
    vif --delete ${1}
    exit 0
}

## parse the arguments
if [ $# -lt 1 ]; then
    usage
fi

ARG=${1}; shift
case ${ARG} in
    "stop" )
        monitoring_stop ${1};;
esac
MONITORED_VIF_ID=${ARG}

## check if the monitoring interface is free
MON_IF_ID=${MONITORED_VIF_ID}
if ifconfig ${MON_IF_NAME}${MON_IF_ID} &>/dev/null; then
    error "monitoring interface ${MON_IF_NAME}${MON_IF_ID} is already in use.\nUse ${0##*/} stop ${MONITORED_VIF_ID} to force stop the monitoring."
fi

## find free monitoring vif index
MON_VIF_ID=$((${VR_MAX_INTERFACES} - ${MON_IF_ID} - 1))
while true; do
    if ! vif --list | grep "^vif0/${MON_VIF_ID}\b" &>/dev/null; then
        break
    fi
    MON_VIF_ID=$((${MON_VIF_ID} - 1))
done

vif --add ${MON_IF_NAME}${MON_IF_ID} --type ${MON_TYPE} --vif ${MONITORED_VIF_ID} \
    --id ${MON_VIF_ID}

## wait for monitoring interface to appear
WAIT=10
while ! ifconfig ${MON_IF_NAME}${MON_IF_ID} &>/dev/null; do
    WAIT=$((${WAIT} - 1))
    if [ "${WAIT}" = "0" ]; then
        error "no interface ${MON_IF_NAME}${MON_IF_ID}"
    fi
done

ifconfig ${MON_IF_NAME}${MON_IF_ID} up

## set signal handler
trap "echo ${0##*/}: deleting vif ${MON_VIF_ID}... && vif --delete ${MON_VIF_ID}" \
    SIGHUP SIGINT SIGQUIT SIGABRT SIGPIPE SIGTERM

## run tcpdump with the rest of arguments
tcpdump -i ${MON_IF_NAME}${MON_IF_ID} $*
