#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

Import('VRouterEnv')
env = VRouterEnv.Clone()

env.Append(CCFLAGS = '-D__DPDK__')
# Uncomment the following to enable SSE4.2 instruction set for CRC hash function
#env.Append(CCFLAGS = '-march=corei7')

env.Library('dp_core', Glob('*.c'))

if 'install' in COMMAND_LINE_TARGETS:
    env.Append(SRC_INSTALL_TARGET = '/dp-core/')
    env.Install(env['SRC_INSTALL_TARGET'], Glob('*.c'))
    env.Alias('install', env['SRC_INSTALL_TARGET'])

# Local Variables:
# mode: python
# End:
